Repository AWS-Cloud-School-6/AIWA-MCP-Helm, pull requests merged in 2024-10, with the labels that each got.

#2 #1 Fix: ECR image 사용
  aiwa-app/templates/deployment.yaml
  aiwa-app/values.yaml
Labels: documentation

#4 #3 Docs test용 svc, dep 업로드
  aiwa-svc-test/dep.yaml
  aiwa-svc-test/svc.yaml
Labels: documentation

#6 #5 Docs: 디렉토리 정리, aiwa-terra 생성
  aiwa-svc-test/dep.yaml
  aiwa-svc-test/svc.yaml
Labels: documentation

#7 #5 create directory
  aiwa-terra/a.txt
Labels: documentation

#9 #8 [Feat]: terraform helm chart 구현
  aiwa-app/templates/deployment.yaml
  aiwa-terra/.helmignore
  aiwa-terra/Chart.yaml
  aiwa-terra/a.txt
  aiwa-terra/index.yaml
  aiwa-terra/templates/NOTES.txt
  aiwa-terra/templates/_helpers.tpl
  aiwa-terra/templates/deployment.yaml
  aiwa-terra/templates/tests/test-connection.yaml
  aiwa-terra/values.yaml
Labels: enhancement

#10 #8 [Fix]: values.yaml 파일 수정
  aiwa-terra/values.yaml
Labels: bug

#12 #11 argocd 연동 문제 해결
  aiwa-terra/templates/deployment.yaml
Labels: bug

#13 [Fix]: argocd 연동 에러 해결
  aiwa-terra/templates/deployment.yaml
Labels: bug

#14 [Fix]: envFrom 수정
  aiwa-terra/templates/deployment.yaml
Labels: bug

#15 [Fix]: envFrom 제거
  aiwa-terra/templates/deployment.yaml
Labels: bug

#16 [Fix]: && 제거
  aiwa-terra/templates/deployment.yaml
Labels: bug

#18 #17 Docs: member upload
  aiwa-member/.helmignore
  aiwa-member/Chart.yaml
  aiwa-member/templates/NOTES.txt
  aiwa-member/templates/_helpers.tpl
  aiwa-member/templates/deployment.yaml
  aiwa-member/templates/tests/test-connection.yaml
  aiwa-member/values.yaml
Labels: documentation

#20 19 docs application 통합 작업
  aiwa-all/.helmignore
  aiwa-all/Chart.yaml
  aiwa-all/index.yaml
  aiwa-all/templates/NOTES.txt
  aiwa-all/templates/_helpers.tpl
  aiwa-all/templates/aiwa-app.yaml
  aiwa-all/templates/aiwa-member.yaml
  aiwa-all/templates/aiwa-terra.yaml
  aiwa-all/templates/tests/test-connection.yaml
  aiwa-all/values.yaml
Labels: documentation
